version: "3.2"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    environment:
      - discovery.type=single-node

  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.2
    ports:
      - 5601:5601
  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: ${SUPERPASS}
      POSTGRES_DB: ${PG_DB}
    volumes:
      - dev_data:/var/lib/postgres/data

  web:
    build: .
    environment:
      DEBUG: "true"
      DATABASE_URL: postgres://postgres:${SUPERPASS}@db:5432/${PG_DB}
      SECRET_KEY: ${SECRET_KEY}
      SUPERUSER: admin
      SUPERPASS: ${SUPERPASS}
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - type: bind
        source: ./backend
        target: /backend
    ports:
      - "${WEB_PORT}:8080"
    depends_on:
      - db
      - elasticsearch

volumes:
  dev_data: